name: miapp
services:
  db:
    image: mysql:9.4
    restart: always
    environment:
      MYSQL_USER_FILE: /var/run/secrets/db_user_name
      MYSQL_PASSWORD_FILE: /var/run/secrets/db_user_password
      MYSQL_ROOT_PASSWORD_FILE: /var/run/secrets/db_root_password
      MYSQL_DATABASE_FILE: /var/run/secrets/db_name
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    secrets:
      - db_root_password
      - db_user_password
      - db_name
      - db_user_name
  backend:
    image: ghcr.io/jfcabrerab/miapp-backend:lab-1
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "4000:4000"
volumes:
  db_data:
secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt
  db_user_password:
    file: ./secrets/db_user_password.txt
  db_name:
    file: ./secrets/db_name.txt
  db_user_name:
    file: ./secrets/db_user_name.txt
